"""empty message

Revision ID: e3041e8c77a2
Revises: c489a7a0a1e7
Create Date: 2023-03-24 17:32:31.406608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3041e8c77a2'
down_revision = 'c489a7a0a1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('createdat', sa.DateTime(), nullable=False),
    sa.Column('updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createdby'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type'], ['types.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('createdat', sa.DateTime(), nullable=False),
    sa.Column('updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roomid'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('createdat', sa.DateTime(), nullable=False),
    sa.Column('updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roomid'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    op.drop_table('messages')
    op.drop_table('rooms')
    # ### end Alembic commands ###