"""empty message

Revision ID: 36258906ad9e
Revises: b52fa56b65bf
Create Date: 2023-03-23 20:16:05.625996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36258906ad9e'
down_revision = 'b52fa56b65bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('profileicon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('createdat', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updatedat', sa.DateTime(), nullable=False))
        batch_op.drop_column('createdAt')
        batch_op.drop_column('lastName')
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('profileIcon')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('profileIcon', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('updatedAt', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('createdAt', sa.DATETIME(), nullable=False))
        batch_op.drop_column('updatedat')
        batch_op.drop_column('createdat')
        batch_op.drop_column('profileicon')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###