"""empty message

Revision ID: b0dc63eb21be
Revises: e3041e8c77a2
Create Date: 2023-03-24 18:01:14.129587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dc63eb21be'
down_revision = 'e3041e8c77a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('updatedat',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdat',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###